// Generated by CoffeeScript 1.3.3
var Constants, Dance, States, Tokens;

Constants = {
  move_threshold: 10,
  time_score_multiplier: 10,
  section_length: 20,
  pause_length: 5,
  score_threshold: 3
};

Tokens = {
  stationary: 0,
  up: 1,
  down: 2,
  left: 3,
  right: 4,
  forward: 5,
  back: 6
};

States = {
  running: 0,
  paused: 1,
  done: 2
};

Dance = {
  dance: [],
  section_events: [],
  section_counter: 0,
  section_end: 0,
  state: States.done,
  register_sample: function(sample) {
    var dt, dx, dy, dz, ea, eb, event_check, sa, sb, ta, tb, time, _ref;
    if (this.state === States.done) {
      return;
    }
    sample = sample.acceleration;
    UI.dbg("" + sample.x + " " + sample.y + " " + sample.z);
    time = Date.now();
    if (this.state === States.paused && time < this.section_end) {
      return;
    } else {
      this.state = States.running;
      this.section_end += Constants.section_length;
    }
    if (time > this.section_end) {
      if (this.section_counter > this.dance.length) {
        this.dance.append(this.section_events);
        this.section_events = [];
        this.section_counter = 0;
        this.section_end += Constants.pause_length;
        this.state = States.paused;
      } else {
        this.section_end += Constants.section_length;
        this.section_counter += 1;
      }
    }
    event_check = false;
    if (sample.x + sample.y + sample.z > Constants.move_threshold) {
      this.section_events.push([sample, time]);
      event_check = true;
    }
    if (this.section_counter < this.dance.length && event_check) {
      ea = this.section_events[-1];
      sa = ea[0];
      ta = ea[1];
      eb = this.dance[-1][this.section_events.length - 1];
      sb = eb[0];
      tb = eb[1];
      _ref = [Math.abs(sa.x - sb.x), Math.abs(sa.y - sb.y), Math.abs(sa.z - sb.z)], dx = _ref[0], dy = _ref[1], dz = _ref[2];
      dt = Constants.time_score_multiplier * Math.abs(ta - tb);
      if (Math.max(dx, dy, dz, dt) > Constants.score_threshold) {
        this.end_dance();
      }
    }
  },
  start_dance: function() {
    this.dance = [];
    return this.state = States.running;
  },
  end_dance: function() {
    this.state = States.done;
    return UI.game_over();
  }
};
