// Generated by CoffeeScript 1.3.3
var Sound;

Sound = {
  files: {},
  init: function(name, path) {
    var f, n,
      _this = this;
    this.files[name] = f = new Audio(path);
    f.play();
    if (f.readyState !== 4) {
      n = function() {
        return false;
      };
      f.addEventListener('canplaythrough', n, false);
      f.addEventListener('load', n, false);
      f.addEventListener('ended', (function() {
        return f.currentTime = 0.1;
      }), false);
      return setTimeout((function() {
        return f.pause();
      }), 1);
    }
  },
  start: function(name) {
    return this.files[name].play();
  }
};

Sound.init('song', 'audio/sweetdaftstarships.mp3');

Sound.init('countdown', 'audio/countdown.mp3');

Sound.init('failure', 'audio/failure.mp3');

Sound.init('swap', 'audio/swap.mp3');

Sound.init('nextplayer', 'audio/nextplayer.mp3');

Sound.init('keepgoing', 'audio/keepgoing.mp3');
