// Generated by CoffeeScript 1.3.3

window.UI = {
  message: function() {
    return document.getElementById("message");
  },
  msg: function(m) {
    return this.message().innerHTML = m;
  },
  action: function() {
    return document.getElementById("action");
  },
  ref: function(m) {
    return this.action().innerHTML = m;
  },
  states: {
    initial: 0,
    active: 1,
    lost: 2
  },
  state: this.states.initial,
  startCountdown: function() {
    this.stop();
    this.msg('5');
    window.setTimeout("UI.msg('4');", 2000);
    window.setTimeout("UI.msg('3');", 3000);
    window.setTimeout("UI.msg('2');", 4000);
    window.setTimeout("UI.msg('1');", 5000);
    return window.setTimeout("UI.start();", 6000);
  },
  stop: function() {
    this.state = this.states.initial;
    this.ref('start');
    return window.ondevicemotion = false;
  },
  start: function() {
    this.state = this.states.active;
    this.ref('reset');
    this.msg('Dance.');
    return window.ondevicemotion = Dance.register_sample;
  },
  game_over: function() {
    this.state = this.states.lost;
    return this.msg('You Lose');
  },
  bind: function() {
    this.ref("start");
    return this.action().onclick = function() {
      UI.startCountdown();
      return false;
    };
  }
};
