// Generated by CoffeeScript 1.3.3
(function() {
  var UI;

  UI = {
    timer: function() {
      return document.getElementById("timer");
    },
    startCountdown: function() {
      this.timer.innerHTML = '5';
      window.setTimeout("UI.timer.innerHTML = '4';", 2000);
      window.setTimeout("UI.timer.innerHTML = '3';", 3000);
      window.setTimeout("UI.timer.innerHTML = '2';", 4000);
      window.setTimeout("UI.timer.innerHTML = '1';", 5000);
      return window.setTimeout("UI.start()", 6000);
    },
    bind: function() {
      var link;
      link = document.getElementById("start");
      link.innerHTML = "GO";
      return link.onclick = function() {
        this.startCountdown();
        return Dance.reset();
      };
    }
  };

}).call(this);
